### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by stefanhuber** [toenu23/electrum-wrapper#1]
```
{ Error: self signed certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```
I think most electrum servers have self signed certificates. I could work around this by setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` are there any other solutions?

**Comment by wandyer** [comment]
I have the same issue.
